version: '3.8'

services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: taste-app
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEV_REDIS_HOST: ${DEV_REDIS_HOST}
      DEV_REDIS_PORT: ${DEV_REDIS_PORT}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION}
      OCR_KEY: ${OCR_KEY}
      NAVER_MAP_CLIENT_ID: ${NAVER_MAP_CLIENT_ID}
      NAVER_MAP_CLIENT_SECRET: ${NAVER_MAP_CLIENT_SECRET}
      NAVER_DATALAB_CLIENT_ID: ${NAVER_DATALAB_CLIENT_ID}
      NAVER_DATALAB_CLIENT_SECRET: ${NAVER_DATALAB_CLIENT_SECRET}
      VAPID_PUBLIC: ${VAPID_PUBLIC}
      VAPID_PRIVATE: ${VAPID_PRIVATE}
      KAKAO_REST_API_KEY: ${KAKAO_REST_API_KEY}
      CLOUD_FRONT_DOMAIN: ${CLOUD_FRONT_DOMAIN}
      OCR_HOST: ${OCR_HOST}
      OCR_PATH: ${OCR_PATH}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_HOST: ${RDS_HOST}
      RDS_PORT: ${RDS_PORT}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

