version: '3.8'

services:
  test-mysql:
    image: mysql:8.0
    container_name: test-mysql
    ports:
      - "3306:3306"  # 테스트용 포트
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  
  test-redis:
    image: redis:7
    container_name: test-redis
    ports:
      - "6379:6379"  # 테스트용 포트
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
