version: '3.8'

services:
  test-mysql:
    image: mysql:8.0
    container_name: test-mysql
    ports:
      - "3306:3306"  # 테스트용 포트
    environment:
      MYSQL_ROOT_PASSWORD: root1111
      MYSQL_DATABASE: test-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot1111" ]
      interval: 10s
      timeout: 10s
      retries: 10

  
  test-redis:
    image: redis:7
    container_name: test-redis
    ports:
      - "6379:6379"  # 테스트용 포트
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
