version: '3.8'
services:
  test-mysql:
    container_name: test-mysql
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: taste_ci_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test1234
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot1234" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: --lower_case_table_names=1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  test-redis:
    image: redis:7
    container_name: test-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
