version: '3.8'
services:
  test-mysql:
    image: mysql:8.0
    container_name: test-mysql
    environment:
      MYSQL_DATABASE: taste
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5

  test-redis:
    image: redis:7
    container_name: test-redis
    ports:
      - "6379:6379"
