version: '3.8'
services:
  test-mysql:
    image: mysql:8.0
    container_name: test-mysql
    environment:
      MYSQL_DATABASE: taste
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1111" ]
      interval: 5s
      timeout: 5s
      retries: 5

  test-redis:
    image: redis:7
    container_name: test-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
