version: '3.8'

services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: taste-app
    ports:
      - "8081:8080"
    #    depends_on:
    #      - db
    #      - redis
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      #      MYSQL_DATABASE: ${MYSQL_DATABASE}
      #      MYSQL_USER: ${MYSQL_USER}
      #      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEV_REDIS_HOST: ${DEV_REDIS_HOST}
      DEV_REDIS_PORT: ${DEV_REDIS_PORT}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION}
      OCR_KEY: ${OCR_KEY}
      NAVER_MAP_CLIENT_ID: ${NAVER_MAP_CLIENT_ID}
      NAVER_MAP_CLIENT_SECRET: ${NAVER_MAP_CLIENT_SECRET}
      NAVER_DATALAB_CLIENT_ID: ${NAVER_DATALAB_CLIENT_ID}
      NAVER_DATALAB_CLIENT_SECRET: ${NAVER_DATALAB_CLIENT_SECRET}
      VAPID_PUBLIC: ${VAPID_PUBLIC}
      VAPID_PRIVATE: ${VAPID_PRIVATE}
      KAKAO_REST_API_KEY: ${KAKAO_REST_API_KEY}
      CLOUD_FRONT_DOMAIN: ${CLOUD_FRONT_DOMAIN}
      OCR_HOST: ${OCR_HOST}
      OCR_PATH: ${OCR_PATH}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_HOST: ${RDS_HOST}
      RDS_PORT: ${RDS_PORT}

#  db:
#    image: postgres:16
#    container_name: taste-db
#    restart: always
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "5433:5432"
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#
#  redis:
#    image: redis:7.0
#    container_name: taste-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#
#volumes:
#  pg_data:
#  redis_data:
