version: '3.8'
services:
  test-postgres:
    container_name: test-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taste_ci_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d taste_ci_test" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  test-redis:
    image: redis:7
    container_name: test-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
