/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum BoardAccessPolicy implements EnumType {

    CLOSED("CLOSED"),

    FCFS("FCFS"),

    OPEN("OPEN"),

    TIMEATTACK("TIMEATTACK");

    private final String literal;

    private BoardAccessPolicy(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static BoardAccessPolicy lookupLiteral(String literal) {
        return EnumType.lookupLiteral(BoardAccessPolicy.class, literal);
    }
}
