/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum NotificationInfoCategory implements EnumType {

    INDIVIDUAL("INDIVIDUAL"),

    MARKETING("MARKETING"),

    SUBSCRIBERS("SUBSCRIBERS"),

    SYSTEM("SYSTEM");

    private final String literal;

    private NotificationInfoCategory(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static NotificationInfoCategory lookupLiteral(String literal) {
        return EnumType.lookupLiteral(NotificationInfoCategory.class, literal);
    }
}
