/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PartyPartyStatus implements EnumType {

    CANCELED("CANCELED"),

    DELETED("DELETED"),

    EXPIRED("EXPIRED"),

    FULL("FULL"),

    RECRUITING("RECRUITING");

    private final String literal;

    private PartyPartyStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static PartyPartyStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(PartyPartyStatus.class, literal);
    }
}
