/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PkLogPkType implements EnumType {

    EVENT("EVENT"),

    LIKE("LIKE"),

    POST("POST"),

    RESET("RESET"),

    REVIEW("REVIEW");

    private final String literal;

    private PkLogPkType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static PkLogPkType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(PkLogPkType.class, literal);
    }
}
