/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BoardImage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long boardId;
    private Long imageId;

    public BoardImage() {}

    public BoardImage(BoardImage value) {
        this.id = value.id;
        this.boardId = value.boardId;
        this.imageId = value.imageId;
    }

    public BoardImage(
        Long id,
        Long boardId,
        Long imageId
    ) {
        this.id = id;
        this.boardId = boardId;
        this.imageId = imageId;
    }

    /**
     * Getter for <code>taste.board_image.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>taste.board_image.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>taste.board_image.board_id</code>.
     */
    public Long getBoardId() {
        return this.boardId;
    }

    /**
     * Setter for <code>taste.board_image.board_id</code>.
     */
    public void setBoardId(Long boardId) {
        this.boardId = boardId;
    }

    /**
     * Getter for <code>taste.board_image.image_id</code>.
     */
    public Long getImageId() {
        return this.imageId;
    }

    /**
     * Setter for <code>taste.board_image.image_id</code>.
     */
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BoardImage other = (BoardImage) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.boardId == null) {
            if (other.boardId != null)
                return false;
        }
        else if (!this.boardId.equals(other.boardId))
            return false;
        if (this.imageId == null) {
            if (other.imageId != null)
                return false;
        }
        else if (!this.imageId.equals(other.imageId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.boardId == null) ? 0 : this.boardId.hashCode());
        result = prime * result + ((this.imageId == null) ? 0 : this.imageId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BoardImage (");

        sb.append(id);
        sb.append(", ").append(boardId);
        sb.append(", ").append(imageId);

        sb.append(")");
        return sb.toString();
    }
}
