/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Likes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private LocalDateTime createdAt;
    private Long boardId;
    private Long userId;

    public Likes() {}

    public Likes(Likes value) {
        this.id = value.id;
        this.createdAt = value.createdAt;
        this.boardId = value.boardId;
        this.userId = value.userId;
    }

    public Likes(
        Long id,
        LocalDateTime createdAt,
        Long boardId,
        Long userId
    ) {
        this.id = id;
        this.createdAt = createdAt;
        this.boardId = boardId;
        this.userId = userId;
    }

    /**
     * Getter for <code>taste.likes.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>taste.likes.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>taste.likes.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>taste.likes.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>taste.likes.board_id</code>.
     */
    public Long getBoardId() {
        return this.boardId;
    }

    /**
     * Setter for <code>taste.likes.board_id</code>.
     */
    public void setBoardId(Long boardId) {
        this.boardId = boardId;
    }

    /**
     * Getter for <code>taste.likes.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>taste.likes.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Likes other = (Likes) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.boardId == null) {
            if (other.boardId != null)
                return false;
        }
        else if (!this.boardId.equals(other.boardId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.boardId == null) ? 0 : this.boardId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Likes (");

        sb.append(id);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(boardId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
