/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationSetting implements Serializable {

    private static final long serialVersionUID = 1L;

    private String category;
    private Boolean accepted;
    private Long userId;

    public NotificationSetting() {}

    public NotificationSetting(NotificationSetting value) {
        this.category = value.category;
        this.accepted = value.accepted;
        this.userId = value.userId;
    }

    public NotificationSetting(
        String category,
        Boolean accepted,
        Long userId
    ) {
        this.category = category;
        this.accepted = accepted;
        this.userId = userId;
    }

    /**
     * Getter for <code>taste.notification_setting.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>taste.notification_setting.category</code>.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for <code>taste.notification_setting.accepted</code>.
     */
    public Boolean getAccepted() {
        return this.accepted;
    }

    /**
     * Setter for <code>taste.notification_setting.accepted</code>.
     */
    public void setAccepted(Boolean accepted) {
        this.accepted = accepted;
    }

    /**
     * Getter for <code>taste.notification_setting.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>taste.notification_setting.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final NotificationSetting other = (NotificationSetting) obj;
        if (this.category == null) {
            if (other.category != null)
                return false;
        }
        else if (!this.category.equals(other.category))
            return false;
        if (this.accepted == null) {
            if (other.accepted != null)
                return false;
        }
        else if (!this.accepted.equals(other.accepted))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        result = prime * result + ((this.accepted == null) ? 0 : this.accepted.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NotificationSetting (");

        sb.append(category);
        sb.append(", ").append(accepted);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
