/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartyMatchInfoFavor implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long favorId;
    private Long partyMatchInfoId;

    public PartyMatchInfoFavor() {}

    public PartyMatchInfoFavor(PartyMatchInfoFavor value) {
        this.id = value.id;
        this.favorId = value.favorId;
        this.partyMatchInfoId = value.partyMatchInfoId;
    }

    public PartyMatchInfoFavor(
        Long id,
        Long favorId,
        Long partyMatchInfoId
    ) {
        this.id = id;
        this.favorId = favorId;
        this.partyMatchInfoId = partyMatchInfoId;
    }

    /**
     * Getter for <code>taste.party_match_info_favor.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>taste.party_match_info_favor.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>taste.party_match_info_favor.favor_id</code>.
     */
    public Long getFavorId() {
        return this.favorId;
    }

    /**
     * Setter for <code>taste.party_match_info_favor.favor_id</code>.
     */
    public void setFavorId(Long favorId) {
        this.favorId = favorId;
    }

    /**
     * Getter for <code>taste.party_match_info_favor.party_match_info_id</code>.
     */
    public Long getPartyMatchInfoId() {
        return this.partyMatchInfoId;
    }

    /**
     * Setter for <code>taste.party_match_info_favor.party_match_info_id</code>.
     */
    public void setPartyMatchInfoId(Long partyMatchInfoId) {
        this.partyMatchInfoId = partyMatchInfoId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PartyMatchInfoFavor other = (PartyMatchInfoFavor) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.favorId == null) {
            if (other.favorId != null)
                return false;
        }
        else if (!this.favorId.equals(other.favorId))
            return false;
        if (this.partyMatchInfoId == null) {
            if (other.partyMatchInfoId != null)
                return false;
        }
        else if (!this.partyMatchInfoId.equals(other.partyMatchInfoId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.favorId == null) ? 0 : this.favorId.hashCode());
        result = prime * result + ((this.partyMatchInfoId == null) ? 0 : this.partyMatchInfoId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PartyMatchInfoFavor (");

        sb.append(id);
        sb.append(", ").append(favorId);
        sb.append(", ").append(partyMatchInfoId);

        sb.append(")");
        return sb.toString();
    }
}
