/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import com.example.jooq.enums.PkCriteriaType;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PkCriteria implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Boolean isActive;
    private Integer point;
    private PkCriteriaType type;

    public PkCriteria() {}

    public PkCriteria(PkCriteria value) {
        this.id = value.id;
        this.isActive = value.isActive;
        this.point = value.point;
        this.type = value.type;
    }

    public PkCriteria(
        Long id,
        Boolean isActive,
        Integer point,
        PkCriteriaType type
    ) {
        this.id = id;
        this.isActive = isActive;
        this.point = point;
        this.type = type;
    }

    /**
     * Getter for <code>taste.pk_criteria.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>taste.pk_criteria.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>taste.pk_criteria.is_active</code>.
     */
    public Boolean getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>taste.pk_criteria.is_active</code>.
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * Getter for <code>taste.pk_criteria.point</code>.
     */
    public Integer getPoint() {
        return this.point;
    }

    /**
     * Setter for <code>taste.pk_criteria.point</code>.
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * Getter for <code>taste.pk_criteria.type</code>.
     */
    public PkCriteriaType getType() {
        return this.type;
    }

    /**
     * Setter for <code>taste.pk_criteria.type</code>.
     */
    public void setType(PkCriteriaType type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PkCriteria other = (PkCriteria) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        if (this.point == null) {
            if (other.point != null)
                return false;
        }
        else if (!this.point.equals(other.point))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        result = prime * result + ((this.point == null) ? 0 : this.point.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PkCriteria (");

        sb.append(id);
        sb.append(", ").append(isActive);
        sb.append(", ").append(point);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
