/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PkTermRank implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer point;
    private Integer ranking;
    private Long pkTermId;
    private Long userId;

    public PkTermRank() {}

    public PkTermRank(PkTermRank value) {
        this.id = value.id;
        this.point = value.point;
        this.ranking = value.ranking;
        this.pkTermId = value.pkTermId;
        this.userId = value.userId;
    }

    public PkTermRank(
        Long id,
        Integer point,
        Integer ranking,
        Long pkTermId,
        Long userId
    ) {
        this.id = id;
        this.point = point;
        this.ranking = ranking;
        this.pkTermId = pkTermId;
        this.userId = userId;
    }

    /**
     * Getter for <code>taste.pk_term_rank.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>taste.pk_term_rank.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>taste.pk_term_rank.point</code>.
     */
    public Integer getPoint() {
        return this.point;
    }

    /**
     * Setter for <code>taste.pk_term_rank.point</code>.
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * Getter for <code>taste.pk_term_rank.ranking</code>.
     */
    public Integer getRanking() {
        return this.ranking;
    }

    /**
     * Setter for <code>taste.pk_term_rank.ranking</code>.
     */
    public void setRanking(Integer ranking) {
        this.ranking = ranking;
    }

    /**
     * Getter for <code>taste.pk_term_rank.pk_term_id</code>.
     */
    public Long getPkTermId() {
        return this.pkTermId;
    }

    /**
     * Setter for <code>taste.pk_term_rank.pk_term_id</code>.
     */
    public void setPkTermId(Long pkTermId) {
        this.pkTermId = pkTermId;
    }

    /**
     * Getter for <code>taste.pk_term_rank.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>taste.pk_term_rank.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PkTermRank other = (PkTermRank) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.point == null) {
            if (other.point != null)
                return false;
        }
        else if (!this.point.equals(other.point))
            return false;
        if (this.ranking == null) {
            if (other.ranking != null)
                return false;
        }
        else if (!this.ranking.equals(other.ranking))
            return false;
        if (this.pkTermId == null) {
            if (other.pkTermId != null)
                return false;
        }
        else if (!this.pkTermId.equals(other.pkTermId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.point == null) ? 0 : this.point.hashCode());
        result = prime * result + ((this.ranking == null) ? 0 : this.ranking.hashCode());
        result = prime * result + ((this.pkTermId == null) ? 0 : this.pkTermId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PkTermRank (");

        sb.append(id);
        sb.append(", ").append(point);
        sb.append(", ").append(ranking);
        sb.append(", ").append(pkTermId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
