/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PkTerm implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private LocalDateTime endDate;
    private LocalDateTime startDate;
    private Integer term;

    public PkTerm() {}

    public PkTerm(PkTerm value) {
        this.id = value.id;
        this.endDate = value.endDate;
        this.startDate = value.startDate;
        this.term = value.term;
    }

    public PkTerm(
        Long id,
        LocalDateTime endDate,
        LocalDateTime startDate,
        Integer term
    ) {
        this.id = id;
        this.endDate = endDate;
        this.startDate = startDate;
        this.term = term;
    }

    /**
     * Getter for <code>taste.pk_term.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>taste.pk_term.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>taste.pk_term.end_date</code>.
     */
    public LocalDateTime getEndDate() {
        return this.endDate;
    }

    /**
     * Setter for <code>taste.pk_term.end_date</code>.
     */
    public void setEndDate(LocalDateTime endDate) {
        this.endDate = endDate;
    }

    /**
     * Getter for <code>taste.pk_term.start_date</code>.
     */
    public LocalDateTime getStartDate() {
        return this.startDate;
    }

    /**
     * Setter for <code>taste.pk_term.start_date</code>.
     */
    public void setStartDate(LocalDateTime startDate) {
        this.startDate = startDate;
    }

    /**
     * Getter for <code>taste.pk_term.term</code>.
     */
    public Integer getTerm() {
        return this.term;
    }

    /**
     * Setter for <code>taste.pk_term.term</code>.
     */
    public void setTerm(Integer term) {
        this.term = term;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PkTerm other = (PkTerm) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.endDate == null) {
            if (other.endDate != null)
                return false;
        }
        else if (!this.endDate.equals(other.endDate))
            return false;
        if (this.startDate == null) {
            if (other.startDate != null)
                return false;
        }
        else if (!this.startDate.equals(other.startDate))
            return false;
        if (this.term == null) {
            if (other.term != null)
                return false;
        }
        else if (!this.term.equals(other.term))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.endDate == null) ? 0 : this.endDate.hashCode());
        result = prime * result + ((this.startDate == null) ? 0 : this.startDate.hashCode());
        result = prime * result + ((this.term == null) ? 0 : this.term.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PkTerm (");

        sb.append(id);
        sb.append(", ").append(endDate);
        sb.append(", ").append(startDate);
        sb.append(", ").append(term);

        sb.append(")");
        return sb.toString();
    }
}
