/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreBucket implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Boolean isOpened;
    private String name;
    private Long userId;

    public StoreBucket() {}

    public StoreBucket(StoreBucket value) {
        this.id = value.id;
        this.isOpened = value.isOpened;
        this.name = value.name;
        this.userId = value.userId;
    }

    public StoreBucket(
        Long id,
        Boolean isOpened,
        String name,
        Long userId
    ) {
        this.id = id;
        this.isOpened = isOpened;
        this.name = name;
        this.userId = userId;
    }

    /**
     * Getter for <code>taste.store_bucket.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>taste.store_bucket.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>taste.store_bucket.is_opened</code>.
     */
    public Boolean getIsOpened() {
        return this.isOpened;
    }

    /**
     * Setter for <code>taste.store_bucket.is_opened</code>.
     */
    public void setIsOpened(Boolean isOpened) {
        this.isOpened = isOpened;
    }

    /**
     * Getter for <code>taste.store_bucket.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>taste.store_bucket.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>taste.store_bucket.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>taste.store_bucket.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final StoreBucket other = (StoreBucket) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.isOpened == null) {
            if (other.isOpened != null)
                return false;
        }
        else if (!this.isOpened.equals(other.isOpened))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.isOpened == null) ? 0 : this.isOpened.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StoreBucket (");

        sb.append(id);
        sb.append(", ").append(isOpened);
        sb.append(", ").append(name);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
