/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMatchCondStore implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long storeId;
    private Long userMatchCondId;

    public UserMatchCondStore() {}

    public UserMatchCondStore(UserMatchCondStore value) {
        this.id = value.id;
        this.storeId = value.storeId;
        this.userMatchCondId = value.userMatchCondId;
    }

    public UserMatchCondStore(
        Long id,
        Long storeId,
        Long userMatchCondId
    ) {
        this.id = id;
        this.storeId = storeId;
        this.userMatchCondId = userMatchCondId;
    }

    /**
     * Getter for <code>taste.user_match_cond_store.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>taste.user_match_cond_store.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>taste.user_match_cond_store.store_id</code>.
     */
    public Long getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>taste.user_match_cond_store.store_id</code>.
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * Getter for <code>taste.user_match_cond_store.user_match_cond_id</code>.
     */
    public Long getUserMatchCondId() {
        return this.userMatchCondId;
    }

    /**
     * Setter for <code>taste.user_match_cond_store.user_match_cond_id</code>.
     */
    public void setUserMatchCondId(Long userMatchCondId) {
        this.userMatchCondId = userMatchCondId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserMatchCondStore other = (UserMatchCondStore) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.storeId == null) {
            if (other.storeId != null)
                return false;
        }
        else if (!this.storeId.equals(other.storeId))
            return false;
        if (this.userMatchCondId == null) {
            if (other.userMatchCondId != null)
                return false;
        }
        else if (!this.userMatchCondId.equals(other.userMatchCondId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.storeId == null) ? 0 : this.storeId.hashCode());
        result = prime * result + ((this.userMatchCondId == null) ? 0 : this.userMatchCondId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserMatchCondStore (");

        sb.append(id);
        sb.append(", ").append(storeId);
        sb.append(", ").append(userMatchCondId);

        sb.append(")");
        return sb.toString();
    }
}
