/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMatchInfoFavor implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long favorId;
    private Long userMatchInfoId;

    public UserMatchInfoFavor() {}

    public UserMatchInfoFavor(UserMatchInfoFavor value) {
        this.id = value.id;
        this.favorId = value.favorId;
        this.userMatchInfoId = value.userMatchInfoId;
    }

    public UserMatchInfoFavor(
        Long id,
        Long favorId,
        Long userMatchInfoId
    ) {
        this.id = id;
        this.favorId = favorId;
        this.userMatchInfoId = userMatchInfoId;
    }

    /**
     * Getter for <code>taste.user_match_info_favor.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>taste.user_match_info_favor.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>taste.user_match_info_favor.favor_id</code>.
     */
    public Long getFavorId() {
        return this.favorId;
    }

    /**
     * Setter for <code>taste.user_match_info_favor.favor_id</code>.
     */
    public void setFavorId(Long favorId) {
        this.favorId = favorId;
    }

    /**
     * Getter for <code>taste.user_match_info_favor.user_match_info_id</code>.
     */
    public Long getUserMatchInfoId() {
        return this.userMatchInfoId;
    }

    /**
     * Setter for <code>taste.user_match_info_favor.user_match_info_id</code>.
     */
    public void setUserMatchInfoId(Long userMatchInfoId) {
        this.userMatchInfoId = userMatchInfoId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserMatchInfoFavor other = (UserMatchInfoFavor) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.favorId == null) {
            if (other.favorId != null)
                return false;
        }
        else if (!this.favorId.equals(other.favorId))
            return false;
        if (this.userMatchInfoId == null) {
            if (other.userMatchInfoId != null)
                return false;
        }
        else if (!this.userMatchInfoId.equals(other.userMatchInfoId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.favorId == null) ? 0 : this.favorId.hashCode());
        result = prime * result + ((this.userMatchInfoId == null) ? 0 : this.userMatchInfoId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserMatchInfoFavor (");

        sb.append(id);
        sb.append(", ").append(favorId);
        sb.append(", ").append(userMatchInfoId);

        sb.append(")");
        return sb.toString();
    }
}
