/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMatchInfoFavorSeq implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long nextVal;

    public UserMatchInfoFavorSeq() {}

    public UserMatchInfoFavorSeq(UserMatchInfoFavorSeq value) {
        this.nextVal = value.nextVal;
    }

    public UserMatchInfoFavorSeq(
        Long nextVal
    ) {
        this.nextVal = nextVal;
    }

    /**
     * Getter for <code>taste.user_match_info_favor_seq.next_val</code>.
     */
    public Long getNextVal() {
        return this.nextVal;
    }

    /**
     * Setter for <code>taste.user_match_info_favor_seq.next_val</code>.
     */
    public void setNextVal(Long nextVal) {
        this.nextVal = nextVal;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserMatchInfoFavorSeq other = (UserMatchInfoFavorSeq) obj;
        if (this.nextVal == null) {
            if (other.nextVal != null)
                return false;
        }
        else if (!this.nextVal.equals(other.nextVal))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.nextVal == null) ? 0 : this.nextVal.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserMatchInfoFavorSeq (");

        sb.append(nextVal);

        sb.append(")");
        return sb.toString();
    }
}
