/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Board;
import com.example.jooq.tables.BoardEvent;
import com.example.jooq.tables.BoardHashtag;
import com.example.jooq.tables.BoardImage;
import com.example.jooq.tables.BucketItem;
import com.example.jooq.tables.Category;
import com.example.jooq.tables.Chat;
import com.example.jooq.tables.Comment;
import com.example.jooq.tables.Event;
import com.example.jooq.tables.Favor;
import com.example.jooq.tables.Follow;
import com.example.jooq.tables.Hashtag;
import com.example.jooq.tables.Image;
import com.example.jooq.tables.Likes;
import com.example.jooq.tables.NotiSeq;
import com.example.jooq.tables.NotificationContent;
import com.example.jooq.tables.NotificationInfo;
import com.example.jooq.tables.NotificationSetting;
import com.example.jooq.tables.Party;
import com.example.jooq.tables.PartyInvitation;
import com.example.jooq.tables.PartyMatchInfo;
import com.example.jooq.tables.PartyMatchInfoFavor;
import com.example.jooq.tables.PartyMatchInfoFavorSeq;
import com.example.jooq.tables.PkCriteria;
import com.example.jooq.tables.PkLog;
import com.example.jooq.tables.PkTerm;
import com.example.jooq.tables.PkTermRank;
import com.example.jooq.tables.Review;
import com.example.jooq.tables.Store;
import com.example.jooq.tables.StoreBucket;
import com.example.jooq.tables.UserFavor;
import com.example.jooq.tables.UserMatchInfo;
import com.example.jooq.tables.UserMatchInfoCategory;
import com.example.jooq.tables.UserMatchInfoCategorySeq;
import com.example.jooq.tables.UserMatchInfoFavor;
import com.example.jooq.tables.UserMatchInfoFavorSeq;
import com.example.jooq.tables.UserMatchInfoStore;
import com.example.jooq.tables.UserMatchInfoStoreSeq;
import com.example.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Taste extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>taste</code>
     */
    public static final Taste TASTE = new Taste();

    /**
     * The table <code>taste.board</code>.
     */
    public final Board BOARD = Board.BOARD;

    /**
     * The table <code>taste.board_event</code>.
     */
    public final BoardEvent BOARD_EVENT = BoardEvent.BOARD_EVENT;

    /**
     * The table <code>taste.board_hashtag</code>.
     */
    public final BoardHashtag BOARD_HASHTAG = BoardHashtag.BOARD_HASHTAG;

    /**
     * The table <code>taste.board_image</code>.
     */
    public final BoardImage BOARD_IMAGE = BoardImage.BOARD_IMAGE;

    /**
     * The table <code>taste.bucket_item</code>.
     */
    public final BucketItem BUCKET_ITEM = BucketItem.BUCKET_ITEM;

    /**
     * The table <code>taste.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>taste.chat</code>.
     */
    public final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>taste.comment</code>.
     */
    public final Comment COMMENT = Comment.COMMENT;

    /**
     * The table <code>taste.event</code>.
     */
    public final Event EVENT = Event.EVENT;

    /**
     * The table <code>taste.favor</code>.
     */
    public final Favor FAVOR = Favor.FAVOR;

    /**
     * The table <code>taste.follow</code>.
     */
    public final Follow FOLLOW = Follow.FOLLOW;

    /**
     * The table <code>taste.hashtag</code>.
     */
    public final Hashtag HASHTAG = Hashtag.HASHTAG;

    /**
     * The table <code>taste.image</code>.
     */
    public final Image IMAGE = Image.IMAGE;

    /**
     * The table <code>taste.likes</code>.
     */
    public final Likes LIKES = Likes.LIKES;

    /**
     * The table <code>taste.noti_seq</code>.
     */
    public final NotiSeq NOTI_SEQ = NotiSeq.NOTI_SEQ;

    /**
     * The table <code>taste.notification_content</code>.
     */
    public final NotificationContent NOTIFICATION_CONTENT = NotificationContent.NOTIFICATION_CONTENT;

    /**
     * The table <code>taste.notification_info</code>.
     */
    public final NotificationInfo NOTIFICATION_INFO = NotificationInfo.NOTIFICATION_INFO;

    /**
     * The table <code>taste.notification_setting</code>.
     */
    public final NotificationSetting NOTIFICATION_SETTING = NotificationSetting.NOTIFICATION_SETTING;

    /**
     * The table <code>taste.party</code>.
     */
    public final Party PARTY = Party.PARTY;

    /**
     * The table <code>taste.party_invitation</code>.
     */
    public final PartyInvitation PARTY_INVITATION = PartyInvitation.PARTY_INVITATION;

    /**
     * The table <code>taste.party_match_info</code>.
     */
    public final PartyMatchInfo PARTY_MATCH_INFO = PartyMatchInfo.PARTY_MATCH_INFO;

    /**
     * The table <code>taste.party_match_info_favor</code>.
     */
    public final PartyMatchInfoFavor PARTY_MATCH_INFO_FAVOR = PartyMatchInfoFavor.PARTY_MATCH_INFO_FAVOR;

    /**
     * The table <code>taste.party_match_info_favor_seq</code>.
     */
    public final PartyMatchInfoFavorSeq PARTY_MATCH_INFO_FAVOR_SEQ = PartyMatchInfoFavorSeq.PARTY_MATCH_INFO_FAVOR_SEQ;

    /**
     * The table <code>taste.pk_criteria</code>.
     */
    public final PkCriteria PK_CRITERIA = PkCriteria.PK_CRITERIA;

    /**
     * The table <code>taste.pk_log</code>.
     */
    public final PkLog PK_LOG = PkLog.PK_LOG;

    /**
     * The table <code>taste.pk_term</code>.
     */
    public final PkTerm PK_TERM = PkTerm.PK_TERM;

    /**
     * The table <code>taste.pk_term_rank</code>.
     */
    public final PkTermRank PK_TERM_RANK = PkTermRank.PK_TERM_RANK;

    /**
     * The table <code>taste.review</code>.
     */
    public final Review REVIEW = Review.REVIEW;

    /**
     * The table <code>taste.store</code>.
     */
    public final Store STORE = Store.STORE;

    /**
     * The table <code>taste.store_bucket</code>.
     */
    public final StoreBucket STORE_BUCKET = StoreBucket.STORE_BUCKET;

    /**
     * The table <code>taste.user_favor</code>.
     */
    public final UserFavor USER_FAVOR = UserFavor.USER_FAVOR;

    /**
     * The table <code>taste.user_match_info</code>.
     */
    public final UserMatchInfo USER_MATCH_INFO = UserMatchInfo.USER_MATCH_INFO;

    /**
     * The table <code>taste.user_match_info_category</code>.
     */
    public final UserMatchInfoCategory USER_MATCH_INFO_CATEGORY = UserMatchInfoCategory.USER_MATCH_INFO_CATEGORY;

    /**
     * The table <code>taste.user_match_info_category_seq</code>.
     */
    public final UserMatchInfoCategorySeq USER_MATCH_INFO_CATEGORY_SEQ = UserMatchInfoCategorySeq.USER_MATCH_INFO_CATEGORY_SEQ;

    /**
     * The table <code>taste.user_match_info_favor</code>.
     */
    public final UserMatchInfoFavor USER_MATCH_INFO_FAVOR = UserMatchInfoFavor.USER_MATCH_INFO_FAVOR;

    /**
     * The table <code>taste.user_match_info_favor_seq</code>.
     */
    public final UserMatchInfoFavorSeq USER_MATCH_INFO_FAVOR_SEQ = UserMatchInfoFavorSeq.USER_MATCH_INFO_FAVOR_SEQ;

    /**
     * The table <code>taste.user_match_info_store</code>.
     */
    public final UserMatchInfoStore USER_MATCH_INFO_STORE = UserMatchInfoStore.USER_MATCH_INFO_STORE;

    /**
     * The table <code>taste.user_match_info_store_seq</code>.
     */
    public final UserMatchInfoStoreSeq USER_MATCH_INFO_STORE_SEQ = UserMatchInfoStoreSeq.USER_MATCH_INFO_STORE_SEQ;

    /**
     * The table <code>taste.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Taste() {
        super("taste", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Board.BOARD,
            BoardEvent.BOARD_EVENT,
            BoardHashtag.BOARD_HASHTAG,
            BoardImage.BOARD_IMAGE,
            BucketItem.BUCKET_ITEM,
            Category.CATEGORY,
            Chat.CHAT,
            Comment.COMMENT,
            Event.EVENT,
            Favor.FAVOR,
            Follow.FOLLOW,
            Hashtag.HASHTAG,
            Image.IMAGE,
            Likes.LIKES,
            NotiSeq.NOTI_SEQ,
            NotificationContent.NOTIFICATION_CONTENT,
            NotificationInfo.NOTIFICATION_INFO,
            NotificationSetting.NOTIFICATION_SETTING,
            Party.PARTY,
            PartyInvitation.PARTY_INVITATION,
            PartyMatchInfo.PARTY_MATCH_INFO,
            PartyMatchInfoFavor.PARTY_MATCH_INFO_FAVOR,
            PartyMatchInfoFavorSeq.PARTY_MATCH_INFO_FAVOR_SEQ,
            PkCriteria.PK_CRITERIA,
            PkLog.PK_LOG,
            PkTerm.PK_TERM,
            PkTermRank.PK_TERM_RANK,
            Review.REVIEW,
            Store.STORE,
            StoreBucket.STORE_BUCKET,
            UserFavor.USER_FAVOR,
            UserMatchInfo.USER_MATCH_INFO,
            UserMatchInfoCategory.USER_MATCH_INFO_CATEGORY,
            UserMatchInfoCategorySeq.USER_MATCH_INFO_CATEGORY_SEQ,
            UserMatchInfoFavor.USER_MATCH_INFO_FAVOR,
            UserMatchInfoFavorSeq.USER_MATCH_INFO_FAVOR_SEQ,
            UserMatchInfoStore.USER_MATCH_INFO_STORE,
            UserMatchInfoStoreSeq.USER_MATCH_INFO_STORE_SEQ,
            Users.USERS
        );
    }
}
