/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.daos;


import com.example.jooq.tables.Likes;
import com.example.jooq.tables.records.LikesRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LikesDao extends DAOImpl<LikesRecord, com.example.jooq.tables.pojos.Likes, Long> {

    /**
     * Create a new LikesDao without any configuration
     */
    public LikesDao() {
        super(Likes.LIKES, com.example.jooq.tables.pojos.Likes.class);
    }

    /**
     * Create a new LikesDao with an attached configuration
     */
    public LikesDao(Configuration configuration) {
        super(Likes.LIKES, com.example.jooq.tables.pojos.Likes.class, configuration);
    }

    @Override
    public Long getId(com.example.jooq.tables.pojos.Likes object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jooq.tables.pojos.Likes> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Likes.LIKES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.jooq.tables.pojos.Likes> fetchById(Long... values) {
        return fetch(Likes.LIKES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.jooq.tables.pojos.Likes fetchOneById(Long value) {
        return fetchOne(Likes.LIKES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.example.jooq.tables.pojos.Likes> fetchOptionalById(Long value) {
        return fetchOptional(Likes.LIKES.ID, value);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jooq.tables.pojos.Likes> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Likes.LIKES.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.example.jooq.tables.pojos.Likes> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(Likes.LIKES.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>board_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jooq.tables.pojos.Likes> fetchRangeOfBoardId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Likes.LIKES.BOARD_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>board_id IN (values)</code>
     */
    public List<com.example.jooq.tables.pojos.Likes> fetchByBoardId(Long... values) {
        return fetch(Likes.LIKES.BOARD_ID, values);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jooq.tables.pojos.Likes> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Likes.LIKES.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.example.jooq.tables.pojos.Likes> fetchByUserId(Long... values) {
        return fetch(Likes.LIKES.USER_ID, values);
    }
}
