/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.daos;


import com.example.jooq.tables.UserMatchInfoFavor;
import com.example.jooq.tables.records.UserMatchInfoFavorRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMatchInfoFavorDao extends DAOImpl<UserMatchInfoFavorRecord, com.example.jooq.tables.pojos.UserMatchInfoFavor, Long> {

    /**
     * Create a new UserMatchInfoFavorDao without any configuration
     */
    public UserMatchInfoFavorDao() {
        super(UserMatchInfoFavor.USER_MATCH_INFO_FAVOR, com.example.jooq.tables.pojos.UserMatchInfoFavor.class);
    }

    /**
     * Create a new UserMatchInfoFavorDao with an attached configuration
     */
    public UserMatchInfoFavorDao(Configuration configuration) {
        super(UserMatchInfoFavor.USER_MATCH_INFO_FAVOR, com.example.jooq.tables.pojos.UserMatchInfoFavor.class, configuration);
    }

    @Override
    public Long getId(com.example.jooq.tables.pojos.UserMatchInfoFavor object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jooq.tables.pojos.UserMatchInfoFavor> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(UserMatchInfoFavor.USER_MATCH_INFO_FAVOR.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.jooq.tables.pojos.UserMatchInfoFavor> fetchById(Long... values) {
        return fetch(UserMatchInfoFavor.USER_MATCH_INFO_FAVOR.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.jooq.tables.pojos.UserMatchInfoFavor fetchOneById(Long value) {
        return fetchOne(UserMatchInfoFavor.USER_MATCH_INFO_FAVOR.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.example.jooq.tables.pojos.UserMatchInfoFavor> fetchOptionalById(Long value) {
        return fetchOptional(UserMatchInfoFavor.USER_MATCH_INFO_FAVOR.ID, value);
    }

    /**
     * Fetch records that have <code>favor_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jooq.tables.pojos.UserMatchInfoFavor> fetchRangeOfFavorId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(UserMatchInfoFavor.USER_MATCH_INFO_FAVOR.FAVOR_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>favor_id IN (values)</code>
     */
    public List<com.example.jooq.tables.pojos.UserMatchInfoFavor> fetchByFavorId(Long... values) {
        return fetch(UserMatchInfoFavor.USER_MATCH_INFO_FAVOR.FAVOR_ID, values);
    }

    /**
     * Fetch records that have <code>user_match_info_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.example.jooq.tables.pojos.UserMatchInfoFavor> fetchRangeOfUserMatchInfoId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(UserMatchInfoFavor.USER_MATCH_INFO_FAVOR.USER_MATCH_INFO_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_match_info_id IN (values)</code>
     */
    public List<com.example.jooq.tables.pojos.UserMatchInfoFavor> fetchByUserMatchInfoId(Long... values) {
        return fetch(UserMatchInfoFavor.USER_MATCH_INFO_FAVOR.USER_MATCH_INFO_ID, values);
    }
}
