/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.daos;


import com.example.jooq.tables.UserFavor;
import com.example.jooq.tables.records.UserFavorRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFavorDao extends DAOImpl<UserFavorRecord, com.example.jooq.tables.pojos.UserFavor, Long> {

    /**
     * Create a new UserFavorDao without any configuration
     */
    public UserFavorDao() {
        super(UserFavor.USER_FAVOR, com.example.jooq.tables.pojos.UserFavor.class);
    }

    /**
     * Create a new UserFavorDao with an attached configuration
     */
    public UserFavorDao(Configuration configuration) {
        super(UserFavor.USER_FAVOR, com.example.jooq.tables.pojos.UserFavor.class, configuration);
    }

    @Override
    public Long getId(com.example.jooq.tables.pojos.UserFavor object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jooq.tables.pojos.UserFavor> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(UserFavor.USER_FAVOR.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.jooq.tables.pojos.UserFavor> fetchById(Long... values) {
        return fetch(UserFavor.USER_FAVOR.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.jooq.tables.pojos.UserFavor fetchOneById(Long value) {
        return fetchOne(UserFavor.USER_FAVOR.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.example.jooq.tables.pojos.UserFavor> fetchOptionalById(Long value) {
        return fetchOptional(UserFavor.USER_FAVOR.ID, value);
    }

    /**
     * Fetch records that have <code>favor_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jooq.tables.pojos.UserFavor> fetchRangeOfFavorId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(UserFavor.USER_FAVOR.FAVOR_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>favor_id IN (values)</code>
     */
    public List<com.example.jooq.tables.pojos.UserFavor> fetchByFavorId(Long... values) {
        return fetch(UserFavor.USER_FAVOR.FAVOR_ID, values);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jooq.tables.pojos.UserFavor> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(UserFavor.USER_FAVOR.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.example.jooq.tables.pojos.UserFavor> fetchByUserId(Long... values) {
        return fetch(UserFavor.USER_FAVOR.USER_ID, values);
    }
}
