/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Taste;
import com.example.jooq.tables.records.FavorRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Favor extends TableImpl<FavorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>taste.favor</code>
     */
    public static final Favor FAVOR = new Favor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FavorRecord> getRecordType() {
        return FavorRecord.class;
    }

    /**
     * The column <code>taste.favor.id</code>.
     */
    public final TableField<FavorRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>taste.favor.name</code>.
     */
    public final TableField<FavorRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Favor(Name alias, Table<FavorRecord> aliased) {
        this(alias, aliased, null);
    }

    private Favor(Name alias, Table<FavorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>taste.favor</code> table reference
     */
    public Favor(String alias) {
        this(DSL.name(alias), FAVOR);
    }

    /**
     * Create an aliased <code>taste.favor</code> table reference
     */
    public Favor(Name alias) {
        this(alias, FAVOR);
    }

    /**
     * Create a <code>taste.favor</code> table reference
     */
    public Favor() {
        this(DSL.name("favor"), null);
    }

    public <O extends Record> Favor(Table<O> child, ForeignKey<O, FavorRecord> key) {
        super(child, key, FAVOR);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Taste.TASTE;
    }

    @Override
    public Identity<FavorRecord, Long> getIdentity() {
        return (Identity<FavorRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FavorRecord> getPrimaryKey() {
        return Keys.KEY_FAVOR_PRIMARY;
    }

    @Override
    public List<UniqueKey<FavorRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_FAVOR_UKT6R4X9U0EH1A9YG98PAEUNGKD);
    }

    @Override
    public Favor as(String alias) {
        return new Favor(DSL.name(alias), this);
    }

    @Override
    public Favor as(Name alias) {
        return new Favor(alias, this);
    }

    @Override
    public Favor as(Table<?> alias) {
        return new Favor(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Favor rename(String name) {
        return new Favor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Favor rename(Name name) {
        return new Favor(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Favor rename(Table<?> name) {
        return new Favor(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
