/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Taste;
import com.example.jooq.tables.records.HashtagRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hashtag extends TableImpl<HashtagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>taste.hashtag</code>
     */
    public static final Hashtag HASHTAG = new Hashtag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HashtagRecord> getRecordType() {
        return HashtagRecord.class;
    }

    /**
     * The column <code>taste.hashtag.id</code>.
     */
    public final TableField<HashtagRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>taste.hashtag.name</code>.
     */
    public final TableField<HashtagRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Hashtag(Name alias, Table<HashtagRecord> aliased) {
        this(alias, aliased, null);
    }

    private Hashtag(Name alias, Table<HashtagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>taste.hashtag</code> table reference
     */
    public Hashtag(String alias) {
        this(DSL.name(alias), HASHTAG);
    }

    /**
     * Create an aliased <code>taste.hashtag</code> table reference
     */
    public Hashtag(Name alias) {
        this(alias, HASHTAG);
    }

    /**
     * Create a <code>taste.hashtag</code> table reference
     */
    public Hashtag() {
        this(DSL.name("hashtag"), null);
    }

    public <O extends Record> Hashtag(Table<O> child, ForeignKey<O, HashtagRecord> key) {
        super(child, key, HASHTAG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Taste.TASTE;
    }

    @Override
    public Identity<HashtagRecord, Long> getIdentity() {
        return (Identity<HashtagRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<HashtagRecord> getPrimaryKey() {
        return Keys.KEY_HASHTAG_PRIMARY;
    }

    @Override
    public List<UniqueKey<HashtagRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_HASHTAG_UKTNICOK67W95AJKOAU49JEG9FM);
    }

    @Override
    public Hashtag as(String alias) {
        return new Hashtag(DSL.name(alias), this);
    }

    @Override
    public Hashtag as(Name alias) {
        return new Hashtag(alias, this);
    }

    @Override
    public Hashtag as(Table<?> alias) {
        return new Hashtag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hashtag rename(String name) {
        return new Hashtag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hashtag rename(Name name) {
        return new Hashtag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hashtag rename(Table<?> name) {
        return new Hashtag(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
