/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Taste;
import com.example.jooq.tables.records.LikesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Likes extends TableImpl<LikesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>taste.likes</code>
     */
    public static final Likes LIKES = new Likes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LikesRecord> getRecordType() {
        return LikesRecord.class;
    }

    /**
     * The column <code>taste.likes.id</code>.
     */
    public final TableField<LikesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>taste.likes.created_at</code>.
     */
    public final TableField<LikesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>taste.likes.board_id</code>.
     */
    public final TableField<LikesRecord, Long> BOARD_ID = createField(DSL.name("board_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>taste.likes.user_id</code>.
     */
    public final TableField<LikesRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private Likes(Name alias, Table<LikesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Likes(Name alias, Table<LikesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>taste.likes</code> table reference
     */
    public Likes(String alias) {
        this(DSL.name(alias), LIKES);
    }

    /**
     * Create an aliased <code>taste.likes</code> table reference
     */
    public Likes(Name alias) {
        this(alias, LIKES);
    }

    /**
     * Create a <code>taste.likes</code> table reference
     */
    public Likes() {
        this(DSL.name("likes"), null);
    }

    public <O extends Record> Likes(Table<O> child, ForeignKey<O, LikesRecord> key) {
        super(child, key, LIKES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Taste.TASTE;
    }

    @Override
    public Identity<LikesRecord, Long> getIdentity() {
        return (Identity<LikesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<LikesRecord> getPrimaryKey() {
        return Keys.KEY_LIKES_PRIMARY;
    }

    @Override
    public List<ForeignKey<LikesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK5CQ36196J3WW17D7R95QDM4TD, Keys.FKNVX9SEEQQYY71BIJ291PWIWRG);
    }

    private transient Board _board;
    private transient Users _users;

    /**
     * Get the implicit join path to the <code>taste.board</code> table.
     */
    public Board board() {
        if (_board == null)
            _board = new Board(this, Keys.FK5CQ36196J3WW17D7R95QDM4TD);

        return _board;
    }

    /**
     * Get the implicit join path to the <code>taste.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.FKNVX9SEEQQYY71BIJ291PWIWRG);

        return _users;
    }

    @Override
    public Likes as(String alias) {
        return new Likes(DSL.name(alias), this);
    }

    @Override
    public Likes as(Name alias) {
        return new Likes(alias, this);
    }

    @Override
    public Likes as(Table<?> alias) {
        return new Likes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Likes rename(String name) {
        return new Likes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Likes rename(Name name) {
        return new Likes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Likes rename(Table<?> name) {
        return new Likes(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, LocalDateTime, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super LocalDateTime, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super LocalDateTime, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
