/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Taste;
import com.example.jooq.tables.records.NotificationSettingRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationSetting extends TableImpl<NotificationSettingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>taste.notification_setting</code>
     */
    public static final NotificationSetting NOTIFICATION_SETTING = new NotificationSetting();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotificationSettingRecord> getRecordType() {
        return NotificationSettingRecord.class;
    }

    /**
     * The column <code>taste.notification_setting.category</code>.
     */
    public final TableField<NotificationSettingRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>taste.notification_setting.accepted</code>.
     */
    public final TableField<NotificationSettingRecord, Boolean> ACCEPTED = createField(DSL.name("accepted"), SQLDataType.BIT.nullable(false), this, "");

    /**
     * The column <code>taste.notification_setting.user_id</code>.
     */
    public final TableField<NotificationSettingRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private NotificationSetting(Name alias, Table<NotificationSettingRecord> aliased) {
        this(alias, aliased, null);
    }

    private NotificationSetting(Name alias, Table<NotificationSettingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>taste.notification_setting</code> table reference
     */
    public NotificationSetting(String alias) {
        this(DSL.name(alias), NOTIFICATION_SETTING);
    }

    /**
     * Create an aliased <code>taste.notification_setting</code> table reference
     */
    public NotificationSetting(Name alias) {
        this(alias, NOTIFICATION_SETTING);
    }

    /**
     * Create a <code>taste.notification_setting</code> table reference
     */
    public NotificationSetting() {
        this(DSL.name("notification_setting"), null);
    }

    public <O extends Record> NotificationSetting(Table<O> child, ForeignKey<O, NotificationSettingRecord> key) {
        super(child, key, NOTIFICATION_SETTING);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Taste.TASTE;
    }

    @Override
    public UniqueKey<NotificationSettingRecord> getPrimaryKey() {
        return Keys.KEY_NOTIFICATION_SETTING_PRIMARY;
    }

    @Override
    public List<ForeignKey<NotificationSettingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKMK226JK5F6J26WG7MOSHWHDX8);
    }

    private transient Users _users;

    /**
     * Get the implicit join path to the <code>taste.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.FKMK226JK5F6J26WG7MOSHWHDX8);

        return _users;
    }

    @Override
    public NotificationSetting as(String alias) {
        return new NotificationSetting(DSL.name(alias), this);
    }

    @Override
    public NotificationSetting as(Name alias) {
        return new NotificationSetting(alias, this);
    }

    @Override
    public NotificationSetting as(Table<?> alias) {
        return new NotificationSetting(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationSetting rename(String name) {
        return new NotificationSetting(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationSetting rename(Name name) {
        return new NotificationSetting(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationSetting rename(Table<?> name) {
        return new NotificationSetting(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, Boolean, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super Boolean, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super Boolean, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
