/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Taste;
import com.example.jooq.tables.records.UserMatchInfoCategoryRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMatchInfoCategory extends TableImpl<UserMatchInfoCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>taste.user_match_info_category</code>
     */
    public static final UserMatchInfoCategory USER_MATCH_INFO_CATEGORY = new UserMatchInfoCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserMatchInfoCategoryRecord> getRecordType() {
        return UserMatchInfoCategoryRecord.class;
    }

    /**
     * The column <code>taste.user_match_info_category.id</code>.
     */
    public final TableField<UserMatchInfoCategoryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>taste.user_match_info_category.category_id</code>.
     */
    public final TableField<UserMatchInfoCategoryRecord, Long> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>taste.user_match_info_category.user_match_info_id</code>.
     */
    public final TableField<UserMatchInfoCategoryRecord, Long> USER_MATCH_INFO_ID = createField(DSL.name("user_match_info_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private UserMatchInfoCategory(Name alias, Table<UserMatchInfoCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserMatchInfoCategory(Name alias, Table<UserMatchInfoCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>taste.user_match_info_category</code> table
     * reference
     */
    public UserMatchInfoCategory(String alias) {
        this(DSL.name(alias), USER_MATCH_INFO_CATEGORY);
    }

    /**
     * Create an aliased <code>taste.user_match_info_category</code> table
     * reference
     */
    public UserMatchInfoCategory(Name alias) {
        this(alias, USER_MATCH_INFO_CATEGORY);
    }

    /**
     * Create a <code>taste.user_match_info_category</code> table reference
     */
    public UserMatchInfoCategory() {
        this(DSL.name("user_match_info_category"), null);
    }

    public <O extends Record> UserMatchInfoCategory(Table<O> child, ForeignKey<O, UserMatchInfoCategoryRecord> key) {
        super(child, key, USER_MATCH_INFO_CATEGORY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Taste.TASTE;
    }

    @Override
    public UniqueKey<UserMatchInfoCategoryRecord> getPrimaryKey() {
        return Keys.KEY_USER_MATCH_INFO_CATEGORY_PRIMARY;
    }

    @Override
    public List<ForeignKey<UserMatchInfoCategoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKTCLX38YL6R9QBUSQ5XL48220K, Keys.FK7FWRCCH9DPD3TS8M3US4WP7J1);
    }

    private transient Category _category;
    private transient UserMatchInfo _userMatchInfo;

    /**
     * Get the implicit join path to the <code>taste.category</code> table.
     */
    public Category category() {
        if (_category == null)
            _category = new Category(this, Keys.FKTCLX38YL6R9QBUSQ5XL48220K);

        return _category;
    }

    /**
     * Get the implicit join path to the <code>taste.user_match_info</code>
     * table.
     */
    public UserMatchInfo userMatchInfo() {
        if (_userMatchInfo == null)
            _userMatchInfo = new UserMatchInfo(this, Keys.FK7FWRCCH9DPD3TS8M3US4WP7J1);

        return _userMatchInfo;
    }

    @Override
    public UserMatchInfoCategory as(String alias) {
        return new UserMatchInfoCategory(DSL.name(alias), this);
    }

    @Override
    public UserMatchInfoCategory as(Name alias) {
        return new UserMatchInfoCategory(alias, this);
    }

    @Override
    public UserMatchInfoCategory as(Table<?> alias) {
        return new UserMatchInfoCategory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchInfoCategory rename(String name) {
        return new UserMatchInfoCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchInfoCategory rename(Name name) {
        return new UserMatchInfoCategory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchInfoCategory rename(Table<?> name) {
        return new UserMatchInfoCategory(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
