/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Taste;
import com.example.jooq.tables.records.UserMatchInfoFavorRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMatchInfoFavor extends TableImpl<UserMatchInfoFavorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>taste.user_match_info_favor</code>
     */
    public static final UserMatchInfoFavor USER_MATCH_INFO_FAVOR = new UserMatchInfoFavor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserMatchInfoFavorRecord> getRecordType() {
        return UserMatchInfoFavorRecord.class;
    }

    /**
     * The column <code>taste.user_match_info_favor.id</code>.
     */
    public final TableField<UserMatchInfoFavorRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>taste.user_match_info_favor.favor_id</code>.
     */
    public final TableField<UserMatchInfoFavorRecord, Long> FAVOR_ID = createField(DSL.name("favor_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>taste.user_match_info_favor.user_match_info_id</code>.
     */
    public final TableField<UserMatchInfoFavorRecord, Long> USER_MATCH_INFO_ID = createField(DSL.name("user_match_info_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private UserMatchInfoFavor(Name alias, Table<UserMatchInfoFavorRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserMatchInfoFavor(Name alias, Table<UserMatchInfoFavorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>taste.user_match_info_favor</code> table
     * reference
     */
    public UserMatchInfoFavor(String alias) {
        this(DSL.name(alias), USER_MATCH_INFO_FAVOR);
    }

    /**
     * Create an aliased <code>taste.user_match_info_favor</code> table
     * reference
     */
    public UserMatchInfoFavor(Name alias) {
        this(alias, USER_MATCH_INFO_FAVOR);
    }

    /**
     * Create a <code>taste.user_match_info_favor</code> table reference
     */
    public UserMatchInfoFavor() {
        this(DSL.name("user_match_info_favor"), null);
    }

    public <O extends Record> UserMatchInfoFavor(Table<O> child, ForeignKey<O, UserMatchInfoFavorRecord> key) {
        super(child, key, USER_MATCH_INFO_FAVOR);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Taste.TASTE;
    }

    @Override
    public UniqueKey<UserMatchInfoFavorRecord> getPrimaryKey() {
        return Keys.KEY_USER_MATCH_INFO_FAVOR_PRIMARY;
    }

    @Override
    public List<ForeignKey<UserMatchInfoFavorRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK6E89K6DJLSH8YB4F40DEFIJP6, Keys.FK65KV7X2GBSN9GCPVEU8W3R2EF);
    }

    private transient Favor _favor;
    private transient UserMatchInfo _userMatchInfo;

    /**
     * Get the implicit join path to the <code>taste.favor</code> table.
     */
    public Favor favor() {
        if (_favor == null)
            _favor = new Favor(this, Keys.FK6E89K6DJLSH8YB4F40DEFIJP6);

        return _favor;
    }

    /**
     * Get the implicit join path to the <code>taste.user_match_info</code>
     * table.
     */
    public UserMatchInfo userMatchInfo() {
        if (_userMatchInfo == null)
            _userMatchInfo = new UserMatchInfo(this, Keys.FK65KV7X2GBSN9GCPVEU8W3R2EF);

        return _userMatchInfo;
    }

    @Override
    public UserMatchInfoFavor as(String alias) {
        return new UserMatchInfoFavor(DSL.name(alias), this);
    }

    @Override
    public UserMatchInfoFavor as(Name alias) {
        return new UserMatchInfoFavor(alias, this);
    }

    @Override
    public UserMatchInfoFavor as(Table<?> alias) {
        return new UserMatchInfoFavor(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchInfoFavor rename(String name) {
        return new UserMatchInfoFavor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchInfoFavor rename(Name name) {
        return new UserMatchInfoFavor(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchInfoFavor rename(Table<?> name) {
        return new UserMatchInfoFavor(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
