/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Taste;
import com.example.jooq.tables.records.UserMatchInfoCategorySeqRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function1;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMatchInfoCategorySeq extends TableImpl<UserMatchInfoCategorySeqRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>taste.user_match_info_category_seq</code>
     */
    public static final UserMatchInfoCategorySeq USER_MATCH_INFO_CATEGORY_SEQ = new UserMatchInfoCategorySeq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserMatchInfoCategorySeqRecord> getRecordType() {
        return UserMatchInfoCategorySeqRecord.class;
    }

    /**
     * The column <code>taste.user_match_info_category_seq.next_val</code>.
     */
    public final TableField<UserMatchInfoCategorySeqRecord, Long> NEXT_VAL = createField(DSL.name("next_val"), SQLDataType.BIGINT, this, "");

    private UserMatchInfoCategorySeq(Name alias, Table<UserMatchInfoCategorySeqRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserMatchInfoCategorySeq(Name alias, Table<UserMatchInfoCategorySeqRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>taste.user_match_info_category_seq</code> table
     * reference
     */
    public UserMatchInfoCategorySeq(String alias) {
        this(DSL.name(alias), USER_MATCH_INFO_CATEGORY_SEQ);
    }

    /**
     * Create an aliased <code>taste.user_match_info_category_seq</code> table
     * reference
     */
    public UserMatchInfoCategorySeq(Name alias) {
        this(alias, USER_MATCH_INFO_CATEGORY_SEQ);
    }

    /**
     * Create a <code>taste.user_match_info_category_seq</code> table reference
     */
    public UserMatchInfoCategorySeq() {
        this(DSL.name("user_match_info_category_seq"), null);
    }

    public <O extends Record> UserMatchInfoCategorySeq(Table<O> child, ForeignKey<O, UserMatchInfoCategorySeqRecord> key) {
        super(child, key, USER_MATCH_INFO_CATEGORY_SEQ);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Taste.TASTE;
    }

    @Override
    public UserMatchInfoCategorySeq as(String alias) {
        return new UserMatchInfoCategorySeq(DSL.name(alias), this);
    }

    @Override
    public UserMatchInfoCategorySeq as(Name alias) {
        return new UserMatchInfoCategorySeq(alias, this);
    }

    @Override
    public UserMatchInfoCategorySeq as(Table<?> alias) {
        return new UserMatchInfoCategorySeq(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchInfoCategorySeq rename(String name) {
        return new UserMatchInfoCategorySeq(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchInfoCategorySeq rename(Name name) {
        return new UserMatchInfoCategorySeq(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchInfoCategorySeq rename(Table<?> name) {
        return new UserMatchInfoCategorySeq(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function1<? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function1<? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
