/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Taste;
import com.example.jooq.tables.records.UserMatchCondCategoryRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMatchCondCategory extends TableImpl<UserMatchCondCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>taste.user_match_cond_category</code>
     */
    public static final UserMatchCondCategory USER_MATCH_COND_CATEGORY = new UserMatchCondCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserMatchCondCategoryRecord> getRecordType() {
        return UserMatchCondCategoryRecord.class;
    }

    /**
     * The column <code>taste.user_match_cond_category.id</code>.
     */
    public final TableField<UserMatchCondCategoryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>taste.user_match_cond_category.category_id</code>.
     */
    public final TableField<UserMatchCondCategoryRecord, Long> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>taste.user_match_cond_category.user_match_cond_id</code>.
     */
    public final TableField<UserMatchCondCategoryRecord, Long> USER_MATCH_COND_ID = createField(DSL.name("user_match_cond_id"), SQLDataType.BIGINT, this, "");

    private UserMatchCondCategory(Name alias, Table<UserMatchCondCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserMatchCondCategory(Name alias, Table<UserMatchCondCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>taste.user_match_cond_category</code> table
     * reference
     */
    public UserMatchCondCategory(String alias) {
        this(DSL.name(alias), USER_MATCH_COND_CATEGORY);
    }

    /**
     * Create an aliased <code>taste.user_match_cond_category</code> table
     * reference
     */
    public UserMatchCondCategory(Name alias) {
        this(alias, USER_MATCH_COND_CATEGORY);
    }

    /**
     * Create a <code>taste.user_match_cond_category</code> table reference
     */
    public UserMatchCondCategory() {
        this(DSL.name("user_match_cond_category"), null);
    }

    public <O extends Record> UserMatchCondCategory(Table<O> child, ForeignKey<O, UserMatchCondCategoryRecord> key) {
        super(child, key, USER_MATCH_COND_CATEGORY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Taste.TASTE;
    }

    @Override
    public UniqueKey<UserMatchCondCategoryRecord> getPrimaryKey() {
        return Keys.KEY_USER_MATCH_COND_CATEGORY_PRIMARY;
    }

    @Override
    public List<ForeignKey<UserMatchCondCategoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK11QMU2ON1XOMWWRUN60YIFYMT, Keys.FKN720E0SJ5S7GTQUW6L8QTKHJ);
    }

    private transient Category _category;
    private transient UserMatchCond _userMatchCond;

    /**
     * Get the implicit join path to the <code>taste.category</code> table.
     */
    public Category category() {
        if (_category == null)
            _category = new Category(this, Keys.FK11QMU2ON1XOMWWRUN60YIFYMT);

        return _category;
    }

    /**
     * Get the implicit join path to the <code>taste.user_match_cond</code>
     * table.
     */
    public UserMatchCond userMatchCond() {
        if (_userMatchCond == null)
            _userMatchCond = new UserMatchCond(this, Keys.FKN720E0SJ5S7GTQUW6L8QTKHJ);

        return _userMatchCond;
    }

    @Override
    public UserMatchCondCategory as(String alias) {
        return new UserMatchCondCategory(DSL.name(alias), this);
    }

    @Override
    public UserMatchCondCategory as(Name alias) {
        return new UserMatchCondCategory(alias, this);
    }

    @Override
    public UserMatchCondCategory as(Table<?> alias) {
        return new UserMatchCondCategory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchCondCategory rename(String name) {
        return new UserMatchCondCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchCondCategory rename(Name name) {
        return new UserMatchCondCategory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMatchCondCategory rename(Table<?> name) {
        return new UserMatchCondCategory(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
