/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.BoardEvent;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BoardEventRecord extends UpdatableRecordImpl<BoardEventRecord> implements Record5<Long, LocalDateTime, LocalDateTime, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>taste.board_event.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>taste.board_event.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>taste.board_event.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>taste.board_event.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>taste.board_event.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>taste.board_event.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>taste.board_event.board_id</code>.
     */
    public void setBoardId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>taste.board_event.board_id</code>.
     */
    public Long getBoardId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>taste.board_event.event_id</code>.
     */
    public void setEventId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>taste.board_event.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, LocalDateTime, LocalDateTime, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, LocalDateTime, LocalDateTime, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BoardEvent.BOARD_EVENT.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return BoardEvent.BOARD_EVENT.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return BoardEvent.BOARD_EVENT.UPDATED_AT;
    }

    @Override
    public Field<Long> field4() {
        return BoardEvent.BOARD_EVENT.BOARD_ID;
    }

    @Override
    public Field<Long> field5() {
        return BoardEvent.BOARD_EVENT.EVENT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public Long component4() {
        return getBoardId();
    }

    @Override
    public Long component5() {
        return getEventId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public Long value4() {
        return getBoardId();
    }

    @Override
    public Long value5() {
        return getEventId();
    }

    @Override
    public BoardEventRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BoardEventRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public BoardEventRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public BoardEventRecord value4(Long value) {
        setBoardId(value);
        return this;
    }

    @Override
    public BoardEventRecord value5(Long value) {
        setEventId(value);
        return this;
    }

    @Override
    public BoardEventRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BoardEventRecord
     */
    public BoardEventRecord() {
        super(BoardEvent.BOARD_EVENT);
    }

    /**
     * Create a detached, initialised BoardEventRecord
     */
    public BoardEventRecord(Long id, LocalDateTime createdAt, LocalDateTime updatedAt, Long boardId, Long eventId) {
        super(BoardEvent.BOARD_EVENT);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setBoardId(boardId);
        setEventId(eventId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BoardEventRecord
     */
    public BoardEventRecord(com.example.jooq.tables.pojos.BoardEvent value) {
        super(BoardEvent.BOARD_EVENT);

        if (value != null) {
            setId(value.getId());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setBoardId(value.getBoardId());
            setEventId(value.getEventId());
            resetChangedOnNotNull();
        }
    }
}
