/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.enums.ImageType;
import com.example.jooq.tables.Image;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageRecord extends UpdatableRecordImpl<ImageRecord> implements Record9<Long, LocalDateTime, LocalDateTime, String, Long, String, ImageType, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>taste.image.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>taste.image.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>taste.image.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>taste.image.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>taste.image.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>taste.image.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>taste.image.file_extension</code>.
     */
    public void setFileExtension(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>taste.image.file_extension</code>.
     */
    public String getFileExtension() {
        return (String) get(3);
    }

    /**
     * Setter for <code>taste.image.file_size</code>.
     */
    public void setFileSize(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>taste.image.file_size</code>.
     */
    public Long getFileSize() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>taste.image.origin_file_name</code>.
     */
    public void setOriginFileName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>taste.image.origin_file_name</code>.
     */
    public String getOriginFileName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>taste.image.type</code>.
     */
    public void setType(ImageType value) {
        set(6, value);
    }

    /**
     * Getter for <code>taste.image.type</code>.
     */
    public ImageType getType() {
        return (ImageType) get(6);
    }

    /**
     * Setter for <code>taste.image.upload_file_name</code>.
     */
    public void setUploadFileName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>taste.image.upload_file_name</code>.
     */
    public String getUploadFileName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>taste.image.url</code>.
     */
    public void setUrl(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>taste.image.url</code>.
     */
    public String getUrl() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, LocalDateTime, LocalDateTime, String, Long, String, ImageType, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, LocalDateTime, LocalDateTime, String, Long, String, ImageType, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Image.IMAGE.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Image.IMAGE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Image.IMAGE.UPDATED_AT;
    }

    @Override
    public Field<String> field4() {
        return Image.IMAGE.FILE_EXTENSION;
    }

    @Override
    public Field<Long> field5() {
        return Image.IMAGE.FILE_SIZE;
    }

    @Override
    public Field<String> field6() {
        return Image.IMAGE.ORIGIN_FILE_NAME;
    }

    @Override
    public Field<ImageType> field7() {
        return Image.IMAGE.TYPE;
    }

    @Override
    public Field<String> field8() {
        return Image.IMAGE.UPLOAD_FILE_NAME;
    }

    @Override
    public Field<String> field9() {
        return Image.IMAGE.URL;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public String component4() {
        return getFileExtension();
    }

    @Override
    public Long component5() {
        return getFileSize();
    }

    @Override
    public String component6() {
        return getOriginFileName();
    }

    @Override
    public ImageType component7() {
        return getType();
    }

    @Override
    public String component8() {
        return getUploadFileName();
    }

    @Override
    public String component9() {
        return getUrl();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public String value4() {
        return getFileExtension();
    }

    @Override
    public Long value5() {
        return getFileSize();
    }

    @Override
    public String value6() {
        return getOriginFileName();
    }

    @Override
    public ImageType value7() {
        return getType();
    }

    @Override
    public String value8() {
        return getUploadFileName();
    }

    @Override
    public String value9() {
        return getUrl();
    }

    @Override
    public ImageRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ImageRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ImageRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public ImageRecord value4(String value) {
        setFileExtension(value);
        return this;
    }

    @Override
    public ImageRecord value5(Long value) {
        setFileSize(value);
        return this;
    }

    @Override
    public ImageRecord value6(String value) {
        setOriginFileName(value);
        return this;
    }

    @Override
    public ImageRecord value7(ImageType value) {
        setType(value);
        return this;
    }

    @Override
    public ImageRecord value8(String value) {
        setUploadFileName(value);
        return this;
    }

    @Override
    public ImageRecord value9(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public ImageRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, String value4, Long value5, String value6, ImageType value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageRecord
     */
    public ImageRecord() {
        super(Image.IMAGE);
    }

    /**
     * Create a detached, initialised ImageRecord
     */
    public ImageRecord(Long id, LocalDateTime createdAt, LocalDateTime updatedAt, String fileExtension, Long fileSize, String originFileName, ImageType type, String uploadFileName, String url) {
        super(Image.IMAGE);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setFileExtension(fileExtension);
        setFileSize(fileSize);
        setOriginFileName(originFileName);
        setType(type);
        setUploadFileName(uploadFileName);
        setUrl(url);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ImageRecord
     */
    public ImageRecord(com.example.jooq.tables.pojos.Image value) {
        super(Image.IMAGE);

        if (value != null) {
            setId(value.getId());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setFileExtension(value.getFileExtension());
            setFileSize(value.getFileSize());
            setOriginFileName(value.getOriginFileName());
            setType(value.getType());
            setUploadFileName(value.getUploadFileName());
            setUrl(value.getUrl());
            resetChangedOnNotNull();
        }
    }
}
