/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.UserMatchInfoCategory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMatchInfoCategoryRecord extends UpdatableRecordImpl<UserMatchInfoCategoryRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>taste.user_match_info_category.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>taste.user_match_info_category.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>taste.user_match_info_category.category_id</code>.
     */
    public void setCategoryId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>taste.user_match_info_category.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>taste.user_match_info_category.user_match_info_id</code>.
     */
    public void setUserMatchInfoId(Long value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>taste.user_match_info_category.user_match_info_id</code>.
     */
    public Long getUserMatchInfoId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserMatchInfoCategory.USER_MATCH_INFO_CATEGORY.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserMatchInfoCategory.USER_MATCH_INFO_CATEGORY.CATEGORY_ID;
    }

    @Override
    public Field<Long> field3() {
        return UserMatchInfoCategory.USER_MATCH_INFO_CATEGORY.USER_MATCH_INFO_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCategoryId();
    }

    @Override
    public Long component3() {
        return getUserMatchInfoId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCategoryId();
    }

    @Override
    public Long value3() {
        return getUserMatchInfoId();
    }

    @Override
    public UserMatchInfoCategoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserMatchInfoCategoryRecord value2(Long value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public UserMatchInfoCategoryRecord value3(Long value) {
        setUserMatchInfoId(value);
        return this;
    }

    @Override
    public UserMatchInfoCategoryRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserMatchInfoCategoryRecord
     */
    public UserMatchInfoCategoryRecord() {
        super(UserMatchInfoCategory.USER_MATCH_INFO_CATEGORY);
    }

    /**
     * Create a detached, initialised UserMatchInfoCategoryRecord
     */
    public UserMatchInfoCategoryRecord(Long id, Long categoryId, Long userMatchInfoId) {
        super(UserMatchInfoCategory.USER_MATCH_INFO_CATEGORY);

        setId(id);
        setCategoryId(categoryId);
        setUserMatchInfoId(userMatchInfoId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserMatchInfoCategoryRecord
     */
    public UserMatchInfoCategoryRecord(com.example.jooq.tables.pojos.UserMatchInfoCategory value) {
        super(UserMatchInfoCategory.USER_MATCH_INFO_CATEGORY);

        if (value != null) {
            setId(value.getId());
            setCategoryId(value.getCategoryId());
            setUserMatchInfoId(value.getUserMatchInfoId());
            resetChangedOnNotNull();
        }
    }
}
