/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.UserMatchInfoCategorySeq;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMatchInfoCategorySeqRecord extends TableRecordImpl<UserMatchInfoCategorySeqRecord> implements Record1<Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>taste.user_match_info_category_seq.next_val</code>.
     */
    public void setNextVal(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>taste.user_match_info_category_seq.next_val</code>.
     */
    public Long getNextVal() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserMatchInfoCategorySeq.USER_MATCH_INFO_CATEGORY_SEQ.NEXT_VAL;
    }

    @Override
    public Long component1() {
        return getNextVal();
    }

    @Override
    public Long value1() {
        return getNextVal();
    }

    @Override
    public UserMatchInfoCategorySeqRecord value1(Long value) {
        setNextVal(value);
        return this;
    }

    @Override
    public UserMatchInfoCategorySeqRecord values(Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserMatchInfoCategorySeqRecord
     */
    public UserMatchInfoCategorySeqRecord() {
        super(UserMatchInfoCategorySeq.USER_MATCH_INFO_CATEGORY_SEQ);
    }

    /**
     * Create a detached, initialised UserMatchInfoCategorySeqRecord
     */
    public UserMatchInfoCategorySeqRecord(Long nextVal) {
        super(UserMatchInfoCategorySeq.USER_MATCH_INFO_CATEGORY_SEQ);

        setNextVal(nextVal);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserMatchInfoCategorySeqRecord
     */
    public UserMatchInfoCategorySeqRecord(com.example.jooq.tables.pojos.UserMatchInfoCategorySeq value) {
        super(UserMatchInfoCategorySeq.USER_MATCH_INFO_CATEGORY_SEQ);

        if (value != null) {
            setNextVal(value.getNextVal());
            resetChangedOnNotNull();
        }
    }
}
