name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      #OCR, VPC, CLOUDFRONT 추가되어야함
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/your-my-taste
            git pull origin dev
            
            cat <<EOF > .env
  POSTGRES_DB=${{ secrets.POSTGRES_DB }}
  POSTGRES_USER=${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
  DEV_REDIS_HOST=${{ secrets.DEV_REDIS_HOST }}
  DEV_REDIS_PORT=${{ secrets.DEV_REDIS_PORT }}
  S3_BUCKET=${{ secrets.S3_BUCKET }}
  S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
  CLOUD_FRONT_DOMAIN=${{ secrets.CLOUD_FRONT_DOMAIN }}
  S3_REGION=${{ secrets.S3_REGION }}
  OCR_KEY=${{ secrets.OCR_KEY }}
  OCR_HOST=${{ secrets.OCR_HOST }}
  OCR_PATH=${{ secrets.OCR_PATH }}
  VAPID_PUBLIC=${{ secrets.VAPID_PUBLIC }}
  VAPID_PRIVATE=${{ secrets.VAPID_PRIVATE }}
  NAVER_MAP_CLIENT_ID=${{ secrets.NAVER_MAP_CLIENT_ID }}
  NAVER_MAP_CLIENT_SECRET=${{ secrets.NAVER_MAP_CLIENT_SECRET }}
  NAVER_DATALAB_CLIENT_ID=${{ secrets.NAVER_DATALAB_CLIENT_ID }}
  NAVER_DATALAB_CLIENT_SECRET=${{ secrets.NAVER_DATALAB_CLIENT_SECRET }}
  DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE }}
  KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}
  RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}
  RDS_HOST=${{ secrets.RDS_HOST }}
  RDS_PORT=${{ secrets.RDS_PORT }}
  SPRING_PROFILES_ACTIVE=dev
  EOF
  
  
  docker-compose down
  docker-compose pull
  docker-compose up -d --build
