name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      #OCR, VPC, CLOUDFRONT 추가되어야함
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/your-my-taste
            git pull origin dev
            
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "DEV_REDIS_HOST=${{ secrets.DEV_REDIS_HOST }}" >> .env
            echo "DEV_REDIS_PORT=${{ secrets.DEV_REDIS_PORT }}" >> .env
            echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> .env
            echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" >> .env
            echo "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}" >> .env
            echo "CLOUD_FRONT_DOMAIN=${{ secrets.CLOUD_FRONT_DOMAIN }}" >> .env
            echo "S3_REGION=${{ secrets.S3_REGION }}" >> .env
            echo "OCR_KEY=${{ secrets.OCR_KEY }}" >> .env
            echo "OCR_HOST=${{ secrets.OCR_HOST }}" >> .env
            echo "OCR_PATH=${{ secrets.OCR_PATH }}" >> .env
            echo "VAPID_PUBLIC=${{ secrets.VAPID_PUBLIC }}" >> .env
            echo "VAPID_PRIVATE=${{ secrets.VAPID_PRIVATE }}" >> .env            
            echo "NAVER_MAP_CLIENT_ID=${{ secrets.NAVER_MAP_CLIENT_ID }}" >> .env
            echo "NAVER_MAP_CLIENT_SECRET=${{ secrets.NAVER_MAP_CLIENT_SECRET }}" >> .env
            echo "NAVER_DATALAB_CLIENT_ID=${{ secrets.NAVER_DATALAB_CLIENT_ID }}" >> .env
            echo "NAVER_DATALAB_CLIENT_SECRET=${{ secrets.NAVER_DATALAB_CLIENT_SECRET }}" >> .env
            echo "DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE }}" >> .env
            echo "KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}" >> .env
            echo "RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}" >> .env
            echo "RDS_HOST=${{ secrets.RDS_HOST }}" >> .env
            echo "RDS_PORT=${{ secrets.RDS_PORT }}" >> .env
            
            
            
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
