name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  generate-jooq:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: taste_ci_test
      DB_USER: postgres
      DB_PASSWORD: test1234
      DB_SCHEMA: public

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Docker Compose Up (PostgreSQL with init.sql)
        run: docker-compose -f docker-compose.test.ci.yml up -d test-postgres

      - name: Wait for PostgreSQL to be healthy
        run: |
          for i in {1..5}; do
            docker exec test-postgres pg_isready -U postgres && break
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Create .env for Jooq
        run: |
          echo "DB_HOST=localhost"     > .env
          echo "DB_PORT=5432"         >> .env
          echo "DB_NAME=taste_ci_test" >> .env
          echo "DB_USER=postgres"     >> .env
          echo "DB_PASSWORD=test1234" >> .env
          echo "DB_SCHEMA=public" >> .env

      - name: Generate Jooq & Build Jar
        run: ./gradlew clean generateJooq bootJar

      - name: Upload Jooq Code
        uses: actions/upload-artifact@v4
        with:
          name: jooq-code
          path: build/generated-src/jooq

      - name: Upload Built Jar
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: build/libs/*.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_IMAGE }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_IMAGE }}

  build-and-test:
    runs-on: ubuntu-latest
    needs: generate-jooq

    env:
      CI: true
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: taste_ci_test
      DB_USER: postgres
      DB_PASSWORD: test1234
      DB_SCHEMA: public
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      S3_REGION: ${{ secrets.S3_REGION }}
      CLOUD_FRONT_DOMAIN: ${{ secrets.CLOUD_FRONT_DOMAIN }}
      OCR_KEY: ${{ secrets.OCR_KEY }}
      OCR_HOST: ${{ secrets.OCR_HOST }}
      OCR_PATH: ${{ secrets.OCR_PATH }}
      NAVER_MAP_CLIENT_ID: ${{ secrets.NAVER_MAP_CLIENT_ID }}
      NAVER_MAP_CLIENT_SECRET: ${{ secrets.NAVER_MAP_CLIENT_SECRET }}
      NAVER_DATALAB_CLIENT_ID: ${{ secrets.NAVER_DATALAB_CLIENT_ID }}
      NAVER_DATALAB_CLIENT_SECRET: ${{ secrets.NAVER_DATALAB_CLIENT_SECRET }}
      VAPID_PUBLIC: ${{ secrets.VAPID_PUBLIC }}
      VAPID_PRIVATE: ${{ secrets.VAPID_PRIVATE }}
      KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_EMBEDDING_API_KEY: ${{ secrets.OPENAI_EMBEDDING_API_KEY }}
    
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Docker Compose Up
        run: docker-compose -f docker-compose.test.ci.yml up -d

      - name: Wait for PostgreSQL & Redis & RabbitMQ
        run: |
          for i in {1..10}; do
            docker exec test-postgres pg_isready -U postgres &&
            docker exec test-redis redis-cli ping | grep -q PONG &&
            docker exec test-rabbitmq rabbitmqctl status && break
            echo "Waiting for containers to be healthy..."
            sleep 5
          done

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Download Jooq Code
        uses: actions/download-artifact@v4
        with:
          name: jooq-code
          path: build/generated-src/jooq

      - name: Download Built Jar
        uses: actions/download-artifact@v4
        with:
          name: built-jar
          path: build/libs

      - name: Run Unit Tests
        run: ./gradlew unitTest -x generateJooq

      - name: Run Integration Tests
        run: ./gradlew integrationTest
