name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  generate-jooq:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_ROOT_PASSWORD: root1234
          MYSQL_DATABASE: taste_ci_test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: test1234
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot1234"
          --health-interval=5s
          --health-retries=20

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Generate Jooq & Build Jar
        run: ./gradlew clean generateJooq bootJar

      - name: Upload Jooq Code
        uses: actions/upload-artifact@v3
        with:
          name: jooq-code
          path: build/generated-src/jooq

      - name: Upload Built Jar
        uses: actions/upload-artifact@v3
        with:
          name: built-jar
          path: build/libs/*.jar


  build-and-test:
    runs-on: ubuntu-latest
    needs: generate-jooq

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Docker Compose Up
        run: docker-compose -f docker-compose.test.ci.yml up -d

      - name: Wait for DB
        run: |
          for i in {1..10}; do
            docker exec test-mysql mysqladmin ping -h localhost -uroot -proot1234 --silent && \
            docker exec test-redis redis-cli ping | grep -q PONG && break
            echo "Waiting..."
            sleep 5
          done

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Download Jooq Code
        uses: actions/download-artifact@v3
        with:
          name: jooq-code
          path: build/generated-src/jooq

      - name: Download Built Jar
        uses: actions/download-artifact@v3
        with:
          name: built-jar
          path: build/libs

      - name: Run Unit Tests
        run: ./gradlew unitTest -x generateJooq

      - name: Run Integration Tests
        run: ./gradlew integrationTest -x generateJooq
